name: rainbow
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - python=3.7
  - pytorch=1.3
  - pip:
    - matplotlib==3.1.2
    - opencv-python==4.1.2.30
    - pygame==1.9.6
    - pynput==1.6.0
    - tqdm==4.41.0
